In [288]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import ignite
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
pd.set_option("display.max_columns", 101)

In [285]:
from sklearn.neural_network import MLPClassifier

df = pd.read_csv('PBP - 2016 - Week 1.csv')


In [89]:
df.head()


gameId  week homeAbbr awayAbbr  driveIndex  playIndex offenseAbbr  \
0  400868876     1      BAY     NWST           0          0         BAY   
1  400868876     1      BAY     NWST           0          1        NWST   
2  400868876     1      BAY     NWST           0          2        NWST   
3  400868876     1      BAY     NWST           0          3        NWST   
4  400868876     1      BAY     NWST           0          4        NWST   

  defenseAbbr  homeScore  awayScore  quarter  clock     type  down  distance  \
0        NWST          0          0        1  15:00  Kickoff     1        10   
1         BAY          0          0        1  14:55  Timeout     1        10   
2         BAY          0          0        1  14:55     Rush     1        10   
3         BAY          0          0        1  14:55     Rush     2        11   
4         BAY          0          0        1  14:55     Rush     3         3   

   yardLine  yardsGained  endYardLine winner  
0        35           10           86   home  
1        86            0           86   home  
2        86           -1           87   home  
3        87            8           79   home  
4        79            0           79   home

In [42]:
df = df.drop(columns=['homeTeam', 'awayTeam', 'homeId', 'offenseId', 'awayId', 'defenseId', 'offenseTeam', 'defenseTeam', 'year','description', 'wallclock'])

In [99]:
def getWinner(gameId, df):
    final = df.query('gameId == @gameId').iloc[[-1]]
    if(int(final.homeScore) > int(final.awayScore)):
        return 'home'
    else:
        return 'away'

In [100]:
# add a winner label
for index,row in df.iterrows():
    df.at[index,'winner'] = getWinner(row['gameId'], df)

KeyboardInterrupt: 

In [43]:
df.head()

gameId  week homeAbbr awayAbbr  driveIndex  playIndex offenseAbbr  \
0  400868876     1      BAY     NWST           0          0         BAY   
1  400868876     1      BAY     NWST           0          1        NWST   
2  400868876     1      BAY     NWST           0          2        NWST   
3  400868876     1      BAY     NWST           0          3        NWST   
4  400868876     1      BAY     NWST           0          4        NWST   

  defenseAbbr  homeScore  awayScore  quarter  clock     type  down  distance  \
0        NWST          0          0        1  15:00  Kickoff     1        10   
1         BAY          0          0        1  14:55  Timeout     1        10   
2         BAY          0          0        1  14:55     Rush     1        10   
3         BAY          0          0        1  14:55     Rush     2        11   
4         BAY          0          0        1  14:55     Rush     3         3   

   yardLine  yardsGained  endYardLine winner  
0        35           10           86   home  
1        86            0           86   home  
2        86           -1           87   home  
3        87            8           79   home  
4        79            0           79   home

In [45]:
#need to get just the label
labels = []
for index,row in df.iterrows():
    labels.append(getWinner(row['gameId'], df))

In [44]:
 clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

In [51]:
testing_copy = df.copy()
testing_copy = pd.get_dummies(testing_copy)
testing_copy = testing_copy.drop(columns=['winner_away', 'winner_home'])

In [223]:

clf.fit(testing_copy, labels)


ValueError: Found input variables with inconsistent numbers of samples: [16141, 1]

In [82]:
for index,row in testing_copy.iterrows():

    pred = clf.predict(row.values.reshape(1,-1))
    real = getWinner(row['gameId'])
    print(pred[0] + ' vs ' + real)
    

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away

home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away
home vs away

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home
home vs home

In [68]:
week2 = pd.read_csv('PBP - 2016 - Week 2.csv')
week2 = week2.drop(columns=['homeTeam', 'awayTeam', 'homeId', 'offenseId', 'awayId', 'defenseId', 'offenseTeam', 'defenseTeam', 'year','description', 'wallclock'])
week2 = pd.get_dummies(week2)

In [77]:
for index,row in week2.iterrows():
    pred = clf.predict(row.values.reshape(1,-1))
    real = getWinner(row['gameId'])
    print(pred + ' vs ' + real)

ValueError: shapes (1,1367) and (1445,5) not aligned: 1367 (dim 1) != 1445 (dim 0)

In [90]:
week3 = pd.read_csv('PBP - 2016 - Week 3.csv')
week3 = week3.drop(columns=['homeTeam', 'awayTeam', 'homeId', 'offenseId', 'awayId', 'defenseId', 'offenseTeam', 'defenseTeam', 'year','description', 'wallclock'])
# week3 = pd.get_dummies(week3)

In [85]:
for index,row in week3.iterrows():
    pred = clf.predict(row.values.reshape(1,-1))
    real = getWinner(row['gameId'])
    print(pred + ' vs ' + real)

ValueError: shapes (1,1336) and (1445,5) not aligned: 1336 (dim 1) != 1445 (dim 0)

In [86]:
week3.head()

gameId  week  driveIndex  playIndex  homeScore  awayScore  quarter  \
0  400868889     3           0          0          0          0        1   
1  400868889     3           0          1          0          0        1   
2  400868889     3           0          2          0          0        1   
3  400868889     3           0          3          0          0        1   
4  400868889     3           0          4          0          0        1   

   down  distance  yardLine  ...  type_Pass Reception  type_Passing Touchdown  \
0     1        10        35  ...                    0                       0   
1     1        10        75  ...                    0                       0   
2     2         7        72  ...                    1                       0   
3     3         4        69  ...                    0                       0   
4     4         4        69  ...                    0                       0   

   type_Penalty  type_Punt  type_Punt Return Touchdown  type_Rush  \
0             0          0                           0          0   
1             0          0                           0          1   
2             0          0                           0          0   
3             0          0                           0          0   
4             0          1                           0          0   

   type_Rushing Touchdown  type_Sack  type_Safety  type_Timeout  
0                       0          0            0             0  
1                       0          0            0             0  
2                       0          0            0             0  
3                       0          0            0             0  
4                       0          0            0             0  

[5 rows x 1336 columns]

In [91]:
### okay so i need to drop the home abreviations and offense abbreviatsions and just make it based on is home on offense or not

week3.head()

gameId  week homeAbbr awayAbbr  driveIndex  playIndex offenseAbbr  \
0  400868889     3      TCU      ISU           0          0         TCU   
1  400868889     3      TCU      ISU           0          1         ISU   
2  400868889     3      TCU      ISU           0          2         ISU   
3  400868889     3      TCU      ISU           0          3         ISU   
4  400868889     3      TCU      ISU           0          4         ISU   

  defenseAbbr  homeScore  awayScore  quarter  clock               type  down  \
0         ISU          0          0        1  15:00            Kickoff     1   
1         TCU          0          0        1  15:00               Rush     1   
2         TCU          0          0        1  15:00     Pass Reception     2   
3         TCU          0          0        1  15:00  Pass Incompletion     3   
4         TCU          0          0        1  15:00               Punt     4   

   distance  yardLine  yardsGained  endYardLine  
0        10        35            0           75  
1        10        75            3           72  
2         7        72            3           69  
3         4        69            0           69  
4         4        69           30           39

In [92]:
def set_offense_defense(df):
    for index,row in df.iterrows():
        if(row['offenseAbbr'] == row['homeAbbr']):
            df.at[index,'offenseAbbr'] = 'home'
            df.at[index,'defenseAbbr'] = 'away'
        else:
            df.at[index,'offenseAbbr'] = 'away'
            df.at[index,'defenseAbbr'] = 'home'

In [93]:
set_offense_defense(week3)

In [94]:
week3.head()

gameId  week homeAbbr awayAbbr  driveIndex  playIndex offenseAbbr  \
0  400868889     3      TCU      ISU           0          0        home   
1  400868889     3      TCU      ISU           0          1        away   
2  400868889     3      TCU      ISU           0          2        away   
3  400868889     3      TCU      ISU           0          3        away   
4  400868889     3      TCU      ISU           0          4        away   

  defenseAbbr  homeScore  awayScore  quarter  clock               type  down  \
0        away          0          0        1  15:00            Kickoff     1   
1        home          0          0        1  15:00               Rush     1   
2        home          0          0        1  15:00     Pass Reception     2   
3        home          0          0        1  15:00  Pass Incompletion     3   
4        home          0          0        1  15:00               Punt     4   

   distance  yardLine  yardsGained  endYardLine  
0        10        35            0           75  
1        10        75            3           72  
2         7        72            3           69  
3         4        69            0           69  
4         4        69           30           39

In [149]:
test_week3 = week3.copy()
test_week3 = test_week3.drop(columns=['homeAbbr', 'awayAbbr', 'clock'])
test_week3 = pd.get_dummies(test_week3)

In [102]:
labels = []
for index,row in week3.iterrows():
    labels.append(getWinner(row['gameId'], week3))

In [103]:
clf.fit(test_week3, labels)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 2), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [109]:
home = 0
away = 0
for index,row in test_week3.iterrows():
    pred = clf.predict(row.values.reshape(1,-1))
    if(pred[0] == 'home'):
        home+=1
    else:
        away+=1
#     real = getWinner(row['gameId'], test_week3)
#     print(pred[0] + ' vs ' + real)
print(home)
print(away)

12615
0


In [110]:
for index,row in test_week3.iterrows():
    pred = clf.predict_proba(row.values.reshape(1,-1))
    print(pred)

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453 0.64140547]]
[[0.35859453

In [301]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(1, 1)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        print(x)
        x = F.relu(self.fc1(x))
#         x = F.relu(self.fc2(x))
#         x = self.fc3(x)
        return x
    
net = Net()


In [208]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [163]:
week3

gameId  week homeAbbr awayAbbr  driveIndex  playIndex offenseAbbr  \
0      400868889     3      TCU      ISU           0          0        home   
1      400868889     3      TCU      ISU           0          1        away   
2      400868889     3      TCU      ISU           0          2        away   
3      400868889     3      TCU      ISU           0          3        away   
4      400868889     3      TCU      ISU           0          4        away   
...          ...   ...      ...      ...         ...        ...         ...   
12610  400869814     3      ULL      USA          25          4        home   
12611  400869814     3      ULL      USA          25          5        home   
12612  400869814     3      ULL      USA          25          6        home   
12613  400869814     3      ULL      USA          25          7        home   
12614  400869814     3      ULL      USA          25          8        home   

      defenseAbbr  homeScore  awayScore  quarter  clock               type  \
0            away          0          0        1  15:00            Kickoff   
1            home          0          0        1  15:00               Rush   
2            home          0          0        1  15:00     Pass Reception   
3            home          0          0        1  15:00  Pass Incompletion   
4            home          0          0        1  15:00               Punt   
...           ...        ...        ...      ...    ...                ...   
12610        away         28         23        4   3:17               Rush   
12611        away         28         23        4   3:17               Rush   
12612        away         28         23        4   0:23            Timeout   
12613        away         28         23        4   0:23               Rush   
12614        away         28         23        4   0:00        End of Game   

       down  distance  yardLine  yardsGained  endYardLine  
0         1        10        35            0           75  
1         1        10        75            3           72  
2         2         7        72            3           69  
3         3         4        69            0           69  
4         4         4        69           30           39  
...     ...       ...       ...          ...          ...  
12610     1        10        72            4           76  
12611     2         6        76           -1           75  
12612     3         7        75            0           75  
12613     3         7        75           -5           70  
12614     0        12         0            0           70  

[12615 rows x 18 columns]

In [164]:
targets = []
for index,row in week3.iterrows():
    week3.at[index,'winner'] = getWinner(row['gameId'], week3)

In [165]:
target = week3.pop('winner')

In [179]:
target = pd.Categorical(target)
target = target.codes

In [181]:
target

array([1, 1, 1, ..., 1, 1, 1], dtype=int8)

In [217]:
dataset = torch.utils.data.TensorDataset(torch.tensor(test_week3.values).float(), torch.tensor(target).float())

In [218]:
trainloader = torch.utils.data.DataLoader(dataset, 
                                          batch_size=1,
                                          shuffle=True)

In [303]:
import os

model_path = 'cfb-cnn.pt'

if not os.path.exists(model_directory_path):
    os.makedirs(model_directory_path)

if os.path.isfile(model_path):
    # load trained model parameters from disk
    net.load_state_dict(torch.load(model_path))
    print('Loaded model parameters from disk.')
else:
    for epoch in range(2):  # loop over the dataset multiple times

        running_loss = 0.0
        for i, data in enumerate(trainloader, 0):
            # get the inputs
            inputs, labels = data

            # zero the parameter gradients
            optimizer.zero_grad()

            # forward + backward + optimize
            inputs = inputs.unsqueeze(0)
            outputs = net(inputs)
            loss = criterion(outputs.unsqueeze(0), labels.long())
            loss.backward()
            optimizer.step()

            # print statistics
            running_loss += loss.item()
            if i % 2000 == 1999:    # print every 2000 mini-batches
                print('[%d, %5d] loss: %.3f' %
                      (epoch + 1, i + 1, running_loss / 2000))
                running_loss = 0.0
    print('Finished Training.')
    torch.save(net.state_dict(), model_path)
    print('Saved model parameters to disk.')
    

tensor([[[4.0087e+08, 3.0000e+00, 4.0000e+00, 3.0000e+00, 0.0000e+00,
          0.0000e+00, 1.0000e+00, 1.0000e+00, 4.0000e+00, 4.0000e+00,
          3.0000e+00, 1.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
          1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])


RuntimeError: size mismatch, m1: [1 x 44], m2: [1 x 1] at ../aten/src/TH/generic/THTensorMath.cpp:752